Repository MisterPeModder/CyberMatos, pull requests merged in 2023-04, with the labels that each got.

#32 doc: add mermaid diagram
  README.md
Labels: documentation

#33 chore: add Entity & Repository: Order, Product, User
  app/.env
  app/composer.json
  app/composer.lock
  app/config/bundles.php
  app/config/packages/doctrine.yaml
  app/config/packages/doctrine_migrations.yaml
  app/migrations/.gitignore
  app/src/Entity/.gitignore
  app/src/Entity/Order.php
  app/src/Entity/Product.php
  app/src/Entity/User.php
  app/src/Repository/.gitignore
  app/src/Repository/OrderRepository.php
  app/src/Repository/ProductRepository.php
  app/src/Repository/UserRepository.php
  app/symfony.lock
Labels: API

#41 Add the `/api/register` route
  .gitignore
  README.md
  app/.env
  app/composer.json
  app/composer.lock
  app/config/bundles.php
  app/config/packages/nelmio_cors.yaml
  app/config/packages/security.yaml
  app/migrations/Version20230410124126.php
  app/migrations/Version20230424135436.php
  app/src/Component/JsonErrorResponse.php
  app/src/Controller/ApiUserController.php
  app/src/Controller/RegisterController.php
  app/src/Controller/SecurityController.php
  app/src/Entity/AccessToken.php
  app/src/Entity/User.php
  app/src/Repository/AccessTokenRepository.php
  app/src/Repository/UserRepository.php
  app/src/Security/AccessTokenHandler.php
  app/src/Validator/ActuallyNotBlank.php
  app/src/Validator/ActuallyNotBlankValidator.php
  app/src/Validator/UniqueValueInEntity.php
  app/src/Validator/UniqueValueInEntityValidator.php
  app/symfony.lock
  app/tests/Controller/ApiUserControllerTest.php
  app/tests/Controller/UserControllerTest.php
Labels: API

#42 Add the `/api/login` route
  app/migrations/Version20230424152813.php
  app/src/Component/JsonErrorResponse.php
  app/src/Controller/ApiUserController.php
  app/src/Entity/AccessToken.php
  app/tests/Controller/ApiUserControllerTest.php
  docs/e-commerce.postman_collection.json
Labels: API

#51 4 http code associated with correct response
  README.md
  app/cybermatos.sql
  app/src/Controller/ApiCartController.php
  app/src/Controller/ApiOrderController.php
  app/src/Controller/ApiProductController.php
  app/src/Entity/Product.php
  app/src/EventSubscriber/DbExceptionSubscriber.php
  app/tests/Controller/ApiProductControllerTest.php
  docs/Documentation.md
  docs/cybermatos-datas-model.png
  docs/e-commerce.postman_collection.json
  docs/errors.png
Labels: Testing
